export const en = {
  language: "EN",
  hiAdmin: "Hi admin!",
  signin: "Sign In",
  login: "Log in",
  welcomeback: "Welcome Back!",
  email: "Email",
  pleaseEnterEmail: "Please Enter your Email",
  InvalidEmail: "Invalid email address",
  pleaseEnterPassword: "Please Enter your Password",
  password: "Password",
  somethingWentWrongTryAgain: "Something is wrong! Try again",
  PleaseEnterAtLeas8Characters: "Please enter at least 8 characters",
  typeToSearch: "Type to search",
  sortByNew: "Sort By New",
  doctorsAndNurses: "Doctors And Nurses",
  newRequests: "New Requests",
  allDoctors: "All Doctors",
  allNurses: "All Nurses",
  allHospitals: "All Companies",
  logout: "Log Out",
  dashboard: "Dashboard",
  doctors: "Doctors",
  nurses: "Nurses",
  activationProcess: "Activation process",
  submissionDate: "Submission date",
  specialization: "Specialization",
  status: "Status",
  rulesAndPermissions: "Rules & Permissions",
  mySetting: "My Setting",
  allUsers: "All Users",
  addNew: "Add new",
  addUser: "Add user",
  AddUser: "Add User",
  addNewUser: "Add new user",
  editUser: "Edit user",
  cancel: "Cancel",
  pleaseEnterAdminName: "Please enter the admin name",
  pleaseSelectAdminRule: "Please select the admin rule",
  rule: "Rule",
  active: "Active ?",
  userName: "User Name",
  userDetails: "User Details",
  deleteUser: "Delete User",
  edit: "Edit",
  activationForm: "Activation Form",
  action: "Action",
  acceptDoctorNurseConf: "Are you sure you want to Accept The doctor/nurse?",
  acceptDoctorConf: "Are you sure you want to Accept The doctor?",
  acceptNurseConf: "Are you sure you want to Accept The nurse?",
  acceptHospitalConf: "Are you sure you want to Accept The Company?",
  acceptHospitalPackageConf:
    "Are you sure you want to Accept The Company Package?",
  rejectText: "Are you sure you want to Reject The doctor/nurse?",
  rejectHospitalText: "Are you sure you want to Reject The Company?",
  accept: "Accept",
  reject: "Reject",
  reasonsForReject: "Reasons for Reject",
  anotherReason: "Another Reason",
  pleaseTypeTheReason: "Please enter the reason",
  pleaseSelectTheReason: "Please select the reason of rejection",
  explain: "Explain",
  rejected: "Rejected",
  readExplanation: "Read Explanation",
  explanationOfRefusal: "Explanation of refusal",
  editReason: "Edit Reason",
  close: "Close",
  editReasonOfRejection: "Edit Reason of Rejection",
  save: "Save",
  historyRejection: "History Rejection",
  userType: "User Type",
  location: "Location",
  gender: "Gender",
  nationality: "Nationality",
  doctor: "Doctor",
  state: "State",
  adminState: "Admin State",
  businessLicence: "Business Licence",
  Cv: "CV",
  answersToQuestions: "Answers to questions",
  workExeriences: "Work Experiences",
  jobTitle: "Job title",
  speciality: "Speciality",
  startingFrom: "Starting From",
  endingTo: "Ending to",
  companyName: "Company Name",
  website: "Website",
  careerLevel: "Career Level",
  salary: "Salary",
  acheivment: "Acheivment",
  present: "Present",
  careerIntrest: "Career Interests",
  specialty: "Speciality",
  typeOfEstablishment: "Type of establishment",
  germanEducationLevel: "German Education Level",
  cancelRejection: "Cancel Rejection",
  jobType: "Job Type",
  hospital: "Company",
  establishmentType: "Establishment Type",
  responsibleDetails: "Responsible Details",
  ruleOfHiring: "Rule Of Hiring",
  hospitalType: "Company Type",
  hospitalPhone: "Company Phone",
  hospitalEmail: "Company Email",
  bedsNumber: "Beds Number",
  bioAboutHospital: "Bio About Company",
  specialties: "Specialties",
  reasonOfRejection: "Reason Of Rejection",
  completed: "Completed",
  rejection: "Rejection",
  sendMessage: "Send message",
  readMore: "Read More",
  readLess: "Read Less",
  package: "Package",
  packageType: "Package Type",
  rejectHospitalPackage: "Are you sure you want to Reject The Company Package?",
  sendMsg: "Send Message",
  packageDetails: "Package Details",
  pleaseSelectTheMsgType: "Please select the message type",
  type: "Type",
  msgInfo: "Message Info",
  pleaseTypeTitle: "Please enter the message title",
  title: "Title",
  msgBody: "Message Body",
  pleaseEnterMsgBody: "Please enter the message body",
  send: "Send",
  attachments: "Attachments",
  packages: "Packages",
  pleaseEnterSectionTitle: "Please Enter Section Title",
  name: "Name",
  pleaseEnterTheName: "Please Enter the Name",
  sectionTitle: "Section Title",
  cost: "Cost",
  pleaseEnterTheCost: "Please enter the cost",
  numberOfConnections: "Number of Connections",
  pleaseEnterTheNumberOfConnections: "Please enter the number of connections",
  pleaseEnterTheSubscriptionPeriod: "Please enter the subscription period",
  subscriptionPeriod: "Subscription Period",
  pleaseEnterTheFeature: "Please Enter the Feature",
  feature: "Feature",
  saveChanges: "Save Changes",
  addNewPackage: "Add New Package",
  packageDeletedSuccessfully: "Package is deleted Successfully",
  phone: "Phone",
  active: "Active",
  inactive: "Inactive",
  pending: "Pending",
  rejected: "Rejected",
  other: "Other",
  deleted_accounts: "Deleted Accounts",
  hospitals: "Hospitals",
  total_users: "Total Users",
  total_activation: "Total Activation",
  interaction: "Interaction",
  activation_status: "Activation Status",
  activate: "Activate",
  pending: "Pending",
  send: "Send",
  receive: "Receive",
  ContactUsRequests: "Contact us requests",
  reason: "Reason",
  message: "Message",
  read: "Read",
  messageText: "Message Text",
  sendEmailAndNotifications: "Send emails and notification",
  pleaseSelectTheType: "please select the type",
  SelectType: "Select the type",
  ForWhatSpecific: "For?",
  pleaseSelectForWhatSpecific: "Please select for what specific",
  pleaseSelectTheSpecific: "Please select the specific",
  accountName: "Select the account",
  pleaseSelectTheAccount: "Please select the account",
  specific: "Specific",
  messageInfo: "Message Info",
  title: "Title",
  pleaseTypeTheTitle: "Please enter the title",
  sendEmail: "Send Email",
  sendNotification: "Send Notification",
  showVideo: "Show Video",
  noData: "There is no video yet",
  noHistory: "There is no rejection history yet",
  site_settings: "Site Settings",
  landing_page: "Landing Page",
  about_us: "About Us",
  contact_us: "Contact Us",
  faq: "FAQ",
  address: "Address",
  dropdowns: "Dropdowns",
  Section1: "Section 1",
  Section2: "Section 2",
  Section3: "Section 3",
  Section4: "Section 4",
  Section5: "Section 5",
  Section6: "Section 6",
  Section7: "Section 7",
  Section8: "Section 8",
  subtitle: "Subtitle",
  pleaseTypeTheSubtitle: "Please enter the subtitle",
  background: "Background",
  pleaseEnterBackground: "Please enter the background",
  pleaseEnterYourPhone: "Please enter your phone",
  pleaseEnterUrl: "please enter your website link",
  InvalidUrl: "Invalid URL",
  facebook: "Facebook",
  twitter: "Twitter",
  linkedIn: "LinkedIn",
  youtube: "YouTube",
  instagram: "Instagram",
  whatsapp: "Whatsapp",
  browse_it: "Browse it",
  question: "Question",
  pleaseTypeTheQuestion: "Please enter your question",
  answer: "Answer",
  pleaseEnterAnswer: "Please enter your answer",
  delete: "Delete",
  no_data: "No data to display",
  all_doctors_nurses_hospitals: "All Doctors & Nurses & Hospitals",
  all_doctors_nurses: "All Doctors & Nurses",
  all_doctors: "All Doctors",
  all_nurses: "All Nurses",
  all_hospitals: "All Hospitals",
  specific_doctor: "Specific Doctor",
  specific_nurse: "Specific Nurse",
  specific_hospital: "Specific Hospital",
  messages: "Messages",
  nurse: "Nurse",
  general: "General",
  doctors_nurses: "Doctors & Nurses",
  company_name: "Company Name",
  field_cant_be_empty: "Field cannot be empty",
  notCompleted_papers: "Papers not completed",
  others: "Others",
  add: "Add",
  reasonForCommunication: "Reason for communication",
  pleaseEnterYourReason: "Please enter your reason",
  addNewFaq: "Add New FAQ",
  viewDetails: "View Details",
  connection: "Connection",
  job: "Job",
  created_in: "Created in",
  active_package: "Active Package",
  inactive_package: "Inactive Package",
  most_popular: "Most Popular",
  new_package: "New Package",
  pleaseEnterName: "please enter your name",
  connection_number: "Number of connections",
  pleaseEnterConnectionNo: "Please enter number of connections",
  jobs_number: "Number of jobs",
  pleaseEnterJobNo: "Please enter number of jobs",
  deletePackage: "Delete Package",
  createPackage: "Create Package",
  pleaseSelectThePeriod: "Please select the period",
  price: "Price",
  pleaseEnterPrice: "Please enter the price",
  AddPeriod: "Add new period",
  AddFeature: "Add new feature",
  moreInfo: "More Info",
  deletePackageConf: "Are you sure you want to delete this package?",
  delete: "Delete",
  inActivePackageConf: "Are you sure you want to Inactive this package?",
  ActivePackageConf: "Are you sure you want to Active this package?",
  isPopularConf: "Are you sure you want to make this package the most popular?",
  confirm: "Confirm",
  deleteReason: "Are you sure you want to delete this user?",
  reasonsForDelete: "Reasons For Delete",
  temporaryClose: "Temporary Closing",
  employee_name: "Employee Name",
};
