export const ge = {
  language: "DE",
  hiAdmin: "Hallo Admin!",
  signin: "Registrieren",
  login: "Einloggen",
  welcomeback: "Willkommen zurück!",
  email: "E-Mail",
  pleaseEnterEmail: "Bitte geben Sie Ihre E-Mail-Adresse ein",
  InvalidEmail: "Ungültige E-Mail-Adresse",
  pleaseEnterPassword: "Bitte geben Sie Ihr Passwort ein",
  password: "Passwort",
  somethingWentWrongTryAgain:
    "Etwas ist schiefgelaufen! Bitte versuchen Sie es erneut",
  PleaseEnterAtLeas8Characters: "Bitte geben Sie mindestens 8 Zeichen ein",
  typeToSearch: "Suchbegriff eingeben",
  sortByNew: "Nach Neu sortieren",
  doctorsAndNurses: "Ärzte und Pflegefachkräfte",
  newRequests: "Neue Anfragen",
  allDoctors: "Alle Ärzte",
  allNurses: "Alle Pflegefachkräfte",
  allHospitals: "Alle Unternehmen",
  logout: "Abmelden",
  dashboard: "Armaturenbrett",
  doctors: "Ärzte",
  nurses: "Pflegefachkräfte",
  activationProcess: "Aktivierungsprozess",
  name: "Name",
  submissionDate: "Einreichungsdatum",
  specialization: "Spezialisierung",
  status: "Status",
  rulesAndPermissions: "Rollen und Berechtigungen",
  mySetting: "Meine Einstellungen",
  allUsers: "Alle Benutzer",
  addNew: "Hinzufügen",
  addUser: "Benutzer hinzufügen",
  AddUser: "Benutzer hinzufügen",
  addNewUser: "Neuen Benutzer hinzufügen",
  editUser: "Benutzer bearbeiten",
  cancel: "Abbrechen",
  pleaseEnterAdminName: "Bitte geben Sie den Namen des Admins ein",
  pleaseSelectAdminRule: "Bitte wählen Sie die Admin-Rolle aus",
  rule: "Rolle",
  active: "Aktiv?",
  userName: "Benutzername",
  userDetails: "Benutzerdetails",
  deleteUser: "Benutzer löschen",
  edit: "Bearbeiten",
  activationForm: "Aktivierungsformular",
  action: "Aktion",
  acceptDoctorNurseConf:
    "Sind Sie sicher, dass Sie den Arzt / die Pflegefachkraft akzeptieren möchten?",
  acceptDoctorConf: "Sind Sie sicher, dass Sie den Arzt akzeptieren möchten?",
  acceptNurseConf:
    "Sind Sie sicher, dass Sie die Krankenschwester akzeptieren möchten?",
  acceptHospitalConf:
    "Sind Sie sicher, dass Sie das Unternehmen akzeptieren möchten?",
  acceptHospitalPackageConf:
    "Sind Sie sicher, dass Sie das Firmenpaket annehmen möchten?",
  rejectText:
    "Sind Sie sicher, dass Sie den Arzt / die Pflegefachkraft ablehnen möchten?",
  rejectHospitalText:
    "Sind Sie sicher, dass Sie das Unternehmen ablehnen möchten?",
  accept: "Akzeptieren",
  reject: "Ablehnen",
  reasonsForReject: "Ablehnungsgründe",
  anotherReason: "Ein anderer Grund",
  pleaseTypeTheReason: "Bitte geben Sie einen Grund ein",
  pleaseSelectTheReason: "Bitte wählen Sie einen Ablehnungsgrund aus",
  explain: "Erklärung",
  rejected: "Abgelehnt",
  Rejected: "Abgelehnt",
  readExplanation: "Erklärung lesen",
  explanationOfRefusal: "Ablehnungserklärung",
  editReason: "Grund bearbeiten",
  close: "Schliessen",
  editReasonOfRejection: "Ablehnungsgrund bearbeiten",
  save: "Speichern",
  historyRejection: "Ablehnungshistorie",
  userType: "Benutzertyp",
  location: "Standort",
  gender: "Geschlecht",
  nationality: "Nationalität",
  doctor: "Arzt",
  state: "Bundesland",
  adminState: "Admin Status",
  businessLicence: "Ausweisdokument",
  Cv: "CV",
  answersToQuestions: "Fragen und Antworten",
  workExeriences: "Berufserfahrungen",
  jobTitle: "Berufsbezeichnung",
  speciality: "Spezialgebiet",
  startingFrom: "Beginnend ab",
  endingTo: "Endend am",
  companyName: "Unternehmensname",
  website: "Website",
  careerLevel: "Karrierestufe",
  salary: "Gehalt",
  acheivment: "Leistung",
  present: "Gegenwärtig",
  careerIntrest: "Karriereinteressen",
  specialty: "Spezialität",
  typeOfEstablishment: "Art der Einrichtung",
  germanEducationLevel: "Deutsche Sprachniveau",
  cancelRejection: "Ablehnung absagen",
  jobType: "Jobart",
  hospital: "Unternehmen",
  establishmentType: "Art der Einrichtung",
  responsibleDetails: "Verantwortliche Details",
  ruleOfHiring: "Einstellungsregel",
  hospitalType: "Art des Unternehmen",
  hospitalPhone: "Telefon",
  hospitalEmail: "E-Mail Adresse",
  bedsNumber: "Anzahl der Betten",
  bioAboutHospital: "Unternehmensbeschreibung",
  specialties: "Spezialisierungen",
  reasonOfRejection: "Ablehnungsgrund",
  completed: "Abgeschlossen",
  rejection: "Ablehnung",
  sendMessage: "Nachricht senden",
  readMore: "Mehr lesen",
  readLess: "Weniger lesen",
  package: "Paket",
  packageType: "Pakettyp",
  rejectHospitalPackage:
    "Sind Sie sicher, dass Sie das Unternehmenspaket ablehnen möchten?",
  phone: "Telefon",
  deleted_accounts: "Gelöschte Konten",
  hospitals: "Krankenhäuser",
  total_users: "Gesamtzahl der Benutzer",
  total_activation: "vollständige Aktivierung",
  interaction: "Interaktion",
  activation_status: "Aktivierungsstatus",
  activate: "Aktivieren",
  pending: "Ausstehend",
  inactive: "Inaktiv",
  send: "Senden",
  receive: "Empfangen",
  ContactUsRequests: "Kontaktieren Sie uns für Anfragen",
  reason: "Grund",
  message: "Nachricht",
  read: "Lesen",
  messageText: "Nachrichtentext",
  sendEmailAndNotifications: "Senden Sie E-Mails und Benachrichtigungen",
  pleaseSelectTheType: "Bitte wählen Sie den Typ aus",
  SelectType: "Wählen Sie den Typ aus",
  ForWhatSpecific: "für?",
  pleaseSelectForWhatSpecific: "Bitte wählen Sie aus, wofür",
  pleaseSelectTheSpecific: "Bitte wählen Sie das Spezifische aus",
  accountName: "Wählen Sie das Konto aus",
  pleaseSelectTheAccount: "Bitte wählen Sie das Konto aus",
  specific: "Spezifisch",
  messageInfo: "Nachrichteninformationen",
  title: "Titel",
  pleaseTypeTheTitle: "Bitte geben Sie den Titel ein",
  sendEmail: "E-Mail senden",
  sendNotification: "Benachrichtigung senden",
  showVideo: "Video anzeigen",
  noData: "Es gibt noch kein Video",
  noHistory: "Es gibt noch keine Ablehnungshistorie",
  site_settings: "Sie Einstellungen",
  landing_page: "Landingpage",
  about_us: "Über uns",
  contact_us: "Kontaktieren Sie uns",
  faq: "FAQ",
  address: "Adresse",
  dropdowns: "Dropdowns",
  Section1: "Abschnitt 1",
  Section2: "Abschnitt 2",
  Section3: "Abschnitt 3",
  Section4: "Abschnitt 4",
  Section5: "Abschnitt 5",
  Section6: "Abschnitt 6",
  Section7: "Abschnitt 7",
  Section8: "Abschnitt 8",
  subtitle: "Untertitel",
  pleaseTypeTheSubtitle: "Bitte geben Sie den Untertitel ein",
  background: "Hintergrund",
  pleaseEnterBackground: "Bitte geben Sie den Hintergrund ein",
  pleaseEnterYourPhone: "Bitte geben Sie Ihre Telefonnummer ein",
  pleaseEnterUrl: "Bitte geben Sie Ihren Website-Link ein",
  InvalidUrl: "ungültige URL",
  facebook: "Facebook",
  twitter: "Twitter",
  linkedIn: "LinkedIn",
  youtube: "YouTube",
  instagram: "Instagram",
  whatsapp: "Whatsapp",
  browse_it: "Durchsuchen Sie es",
  question: "Frage",
  pleaseTypeTheQuestion: "Bitte geben Sie Ihre Frage ein",
  answer: "Antwort",
  pleaseEnterAnswer: "Bitte gib deine Antwort ein",
  delete: "Löschen",
  no_data: "Keine Daten zum Anzeigen",
  company: "Unternehmen",
  accounts: "Konten",
  messages: "Mitteilungen",
  addNewPackage: "Neues Paket hinzufügen",
  cost: "kosten",
  numberOfConnections: "Anzahl der Verbindungen",
  subscriptionPeriod: "Abonnementzeitraum",
  feature: "Besonderheit",
  saveChanges: "Änderungen speichern",
  inActive: "inaktiv",
  packages: "Pakete",
  sectionTitle: "Abschnittsüberschrift",
  pleaseEnterSectionTitle: "Bitte geben Sie den Abschnittstitel ein",
  pleaseEnterTheName: "Bitte geben Sie den Namen ein",
  pleaseEnterTheCost: "Bitte geben Sie die Kosten ein",
  pleaseEnterTheNumberOfConnections:
    "Bitte geben Sie die Anzahl der Verbindungen ein",
  pleaseEnterTheSubscriptionPeriod:
    "Bitte geben Sie den Abonnementzeitraum ein",
  pleaseEnterTheFeature: "Bitte geben Sie die Funktion ein",
  all_doctors_nurses_hospitals:
    "Alle Ärzte, Krankenschwestern und Krankenhäuser",
  all_doctors_nurses: "Alle Ärzte und Krankenschwestern",
  all_doctors: "Alle Ärzte",
  all_nurses: "Alle Krankenschwestern",
  all_hospitals: "Alle Krankenhäuser",
  specific_doctor: "Spezifischer Arzt",
  specific_nurse: "Spezifische Krankenschwester",
  specific_hospital: "Spezifisches Krankenhaus",
  nurse: "Krankenschwester",
  sendMsg: "Nachricht senden",
  type: "Typ",
  msgBody: "Nachrichtentext",
  general: "Allgemein",
  doctors_nurses: "Ärzte und Krankenschwestern",
  company_name: "Name der Firma",
  field_cant_be_empty: "Das Feld darf nicht leer sein",
  notCompleted_papers: "Papiere nicht abgeschlossen",
  others: "Andere",
  add: "Hinzufügen",
  reasonForCommunication: "Grund für die Kommunikation",
  pleaseEnterYourReason: "Bitte geben Sie Ihren Grund ein",
  addNewFaq: "Neue FAQ hinzufügen",
  viewDetails: "Details anzeigen",
  connection: "Verbindung",
  job: "Arbeit",
  created_in: "Erstellt in",
  active_package: "Aktives Paket",
  inactive_package: "Inaktives Paket",
  most_popular: "Am beliebtesten",
  new_package: "Neues Paket",
  pleaseEnterName: "Bitte geben Sie Ihren Namen ein",
  connection_number: "Anzahl der Verbindungen",
  pleaseEnterConnectionNo: "Bitte geben Sie die Anzahl der Verbindungen ein",
  jobs_number: "Anzahl der Jobs",
  pleaseEnterJobNo: "Bitte geben Sie die Anzahl der Jobs ein",
  deletePackage: "Paket löschen",
  createPackage: "Paket erstellen",
  pleaseSelectThePeriod: "Bitte wählen Sie den Zeitraum aus",
  price: "Preis",
  pleaseEnterPrice: "Bitte geben Sie den Preis ein",
  AddPeriod: "Neuen Zeitraum hinzufügen",
  AddFeature: "Neue Funktion hinzufügen",
  moreInfo: "Mehr Info",
  deletePackageConf: "Sind Sie sicher, dass Sie dieses Paket löschen möchten?",
  delete: "Löschen",
  inActivePackageConf:
    "Sind Sie sicher, dass Sie dieses Paket deaktivieren möchten?",
  ActivePackageConf:
    "Sind Sie sicher, dass Sie dieses Paket aktivieren möchten?",
  isPopularConf:
    "Sind Sie sicher, dass Sie dieses Paket zum beliebtesten Paket machen möchten?",
  confirm: "Bestätigen",
  deleteReason: "Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?",
  reasonsForDelete: "Gründe für die Löschung",
  temporaryClose: "Vorübergehende Schließung",
  employee_name: "Mitarbeitername",
};
